// Utility functions
export {
  parseStackTrace,
  normalizeStackTrace,
  extractRelevantFrames,
  enhanceStackTrace,
  captureStackTrace,
  getCallerInfo,
  type StackFrame,
  type ParsedStackTrace,
} from './stackTrace';

export {
  normalizeError,
  isRetryableError as isErrorRetryable,
  isRecoverableError as isErrorRecoverable,
  isUserFacingError,
  categorizeError,
  createErrorChain,
  flattenErrorChain,
  getErrorFingerprint,
} from './errorNormalizer';

export { debounce, throttle, createDebouncedFunction, delay, timeout, batchProcessor } from './debounce';

export {
  isError,
  isBaseError,
  isNetworkError,
  isHttpError,
  isValidationError,
  isAuthenticationError,
  isTimeoutError,
  isRetryableError,
  isRecoverableError,
  isSyntaxError,
  isReferenceError,
  isTypeError,
  isRangeError,
  isEvalError,
  isURIError,
  isString,
  isNumber,
  isBoolean,
  isObject,
  isFunction,
  isUndefined,
  isNull,
  isNullOrUndefined,
  isArray,
  isDate,
  isRegExp,
  isPromise,
  hasProperty,
  hasMethod,
  isErrorLike,
  isIterable,
  isAsyncIterable,
  hasStatusCode,
  hasErrorCode,
  hasCause,
  hasUserFacingProperty,
  hasRetryableProperty,
} from './typeGuards';
