const FRONTENDS = [
  {
    id: 'mvvm-angular',
    displayName: 'mvvm-angular',
    path: 'apps/mvvm-angular',
    port: 4200,
    framework: 'Angular (ng serve)',
    notes: 'Built with strict ports via Angular CLI; ideal for layout/UX work.',
    command: 'npm run dev',
    recommended: true,
  },
  {
    id: 'mvvm-book',
    displayName: 'mvvm-book',
    path: 'apps/mvvm-book',
    port: 3001,
    framework: 'Next.js',
    notes: 'Next.js marketing book that ships on 3001; uses Next dev server.',
    command: 'npm run dev',
    recommended: true,
  },
  {
    id: 'mvvm-lit',
    displayName: 'mvvm-lit',
    path: 'apps/mvvm-lit',
    port: 5176,
    framework: 'Vite + Lit',
    notes: 'Vite server with strict port.',
    command: 'npm run dev',
    recommended: true,
  },
  {
    id: 'mvvm-marko',
    displayName: 'mvvm-marko',
    path: 'apps/mvvm-marko',
    port: 5739,
    framework: 'Marko + marko-run',
    notes: 'Marko-run with strict port 5739.',
    command: 'npm run dev',
    recommended: true,
  },
  {
    id: 'mvvm-react',
    displayName: 'mvvm-react',
    path: 'apps/mvvm-react',
    port: 5173,
    framework: 'Vite + React',
    notes: 'Default demo and ref-app.',
    command: 'npm run dev',
    recommended: true,
  },
  {
    id: 'mvvm-react-integrated',
    displayName: 'mvvm-react-integrated',
    path: 'apps/mvvm-react-integrated',
    port: 5177,
    framework: 'Vite + React (integrated view)',
    notes: 'Bundles more curated storybooks with the same API.',
    command: 'npm run dev',
    recommended: true,
  },
  {
    id: 'mvvm-react-native',
    displayName: 'mvvm-react-native',
    path: 'apps/mvvm-react-native',
    port: 19006,
    framework: 'Expo (React Native / Web)',
    notes: 'Expo CLI; the web target is 19006, and the CLI shows the QR menu.',
    command: 'npm run dev',
    recommended: false,
  },
  {
    id: 'mvvm-vanilla',
    displayName: 'mvvm-vanilla',
    path: 'apps/mvvm-vanilla',
    port: 5175,
    framework: 'Vite + Vanilla JS',
    notes: 'Lightweight vanilla JS experience based on the shared API.',
    command: 'npm run dev',
    recommended: true,
  },
  {
    id: 'mvvm-vue',
    displayName: 'mvvm-vue',
    path: 'apps/mvvm-vue',
    port: 5174,
    framework: 'Vite + Vue',
    notes: 'Vue 3 + Vite demo with strict port.',
    command: 'npm run dev',
    recommended: true,
  },
];

const DEMO_API = {
  id: 'api',
  displayName: 'apps/api',
  path: 'apps/api',
  port: 8000,
  framework: 'Node + Express',
  notes: 'SQLite + Sequelize demo API that all mvvm-* apps point to.',
  command: 'npm run dev',
};

const TASK_FLOW_TARGETS = [
  {
    id: 'task-flow-api',
    displayName: 'apps/task-flow-api',
    path: 'apps/task-flow-api',
    port: 8001,
    framework: 'Node + Express',
    notes: 'Task Flow GraphQL/Express API (dev meds).',
    command: 'npm run dev',
  },
  {
    id: 'task-flow-ui',
    displayName: 'apps/task-flow-ui',
    path: 'apps/task-flow-ui',
    port: 5178,
    framework: 'Vite + React',
    notes: 'Task Flow UI pinned to 5178 with strictPort.',
    command: 'npm run dev',
  },
];

module.exports = {
  FRONTENDS,
  DEMO_API,
  TASK_FLOW_TARGETS,
};
