name: CI - create-web-loom

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/create-web-loom/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Clean install
        run: |
          rm -rf node_modules
          pnpm install --frozen-lockfile

      - name: Build create-web-loom
        run: pnpm --filter create-web-loom run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: create-web-loom-dist-build-artifacts
          path: packages/create-web-loom/dist/
